In [78]:
import torch
import numpy as np

# Tensors

In [3]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1491e-42, 0.0000e+00],
        [0.0000e+00, 7.6371e-43, 0.0000e+00]])

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.3657, 0.1445, 0.4891],
        [0.2265, 0.9095, 0.3948],
        [0.2160, 0.2956, 0.4488],
        [0.9709, 0.9495, 0.7304],
        [0.9917, 0.5974, 0.1086]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [12]:
x = x.new_ones(5, 3)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.7666, -1.0201,  0.1652],
        [-0.4095,  1.5826,  0.2103],
        [-0.8147,  0.8559,  0.6005],
        [-1.7414,  0.5934, -1.0464],
        [-0.3260,  0.2994, -0.3266]])


In [17]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [55]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3652, -1.0111,  1.0023],
        [ 0.0803,  2.4325,  1.0879],
        [-0.4395,  1.3968,  0.7620],
        [-1.7171,  1.4625, -0.6268],
        [ 0.1429,  0.8042, -0.0089]])


In [56]:
print(torch.add(x, y))

tensor([[-0.3652, -1.0111,  1.0023],
        [ 0.0803,  2.4325,  1.0879],
        [-0.4395,  1.3968,  0.7620],
        [-1.7171,  1.4625, -0.6268],
        [ 0.1429,  0.8042, -0.0089]])


In [57]:
result = torch.empty_like(x)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3652, -1.0111,  1.0023],
        [ 0.0803,  2.4325,  1.0879],
        [-0.4395,  1.3968,  0.7620],
        [-1.7171,  1.4625, -0.6268],
        [ 0.1429,  0.8042, -0.0089]])


In [58]:
y += x
print(y)

tensor([[-0.3652, -1.0111,  1.0023],
        [ 0.0803,  2.4325,  1.0879],
        [-0.4395,  1.3968,  0.7620],
        [-1.7171,  1.4625, -0.6268],
        [ 0.1429,  0.8042, -0.0089]])


In [59]:
print(x[:, 1])

tensor([-1.0201,  1.5826,  0.8559,  0.5934,  0.2994])


In [67]:
# Shallow copies of "reshaped" tensors
x = torch.randn(4, 4)
y = x.view(16)
z =x.view(-1, 8)
print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [68]:
x[1, 1] = -7777

In [72]:
print(x[1, 1])
print(y[4 * 1 + 1])

tensor(-7777.)
tensor(-7777.)


In [73]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4985])
1.4984996318817139


# NumPy Bridge

The tensor & numpy array will share their memory locations

In [74]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [75]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [87]:
a += 1
print(a, b)

[-7. -7. -7. -7. -7.] tensor([-7., -7., -7., -7., -7.], dtype=torch.float64)


In [85]:
a = np.ones(5)
b = torch.from_numpy(a)
a -= 10
print(a, b)

[-9. -9. -9. -9. -9.] tensor([-9., -9., -9., -9., -9.], dtype=torch.float64)


# CUDA

*Won't work on your laptop

In [88]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))