In [1]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

C:\Users\carso\Anaconda3\envs\tflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Tensors

In [2]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("hello world"))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[1]], [[2, 3]])
print("X: {}, shape: {}, dtype:{}".format(x, x.shape, x.dtype))

X: [[2 3]], shape: (1, 2), dtype:<dtype: 'int32'>


## NumPy Compatibility

In [4]:
nparr = np.ones(shape=(3, 3))
print(nparr)
tensor = tf.multiply(nparr, 42)
# print(tensor)
print("TensorFlow ops convert np arrays to Tensors automatically:\n{}".format(tensor))
print("And NumPy operations convert tensors to numpy arrays automatically:\n{}".format(np.add(tensor, 1)))
print("The .numpy() method explicitly converts a Tensor to a numpy array:\n{}".format(tensor.numpy()))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
TensorFlow ops convert np arrays to Tensors automatically:
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
And NumPy operations convert tensors to numpy arrays automatically:
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array:
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


# Datasets

## Create a source dataset

In [5]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write(
"""Line 1
Line 2
Line 3
"""
    )

ds_file = tf.data.TextLineDataset(filename)

## Apply transformations

In [6]:
ds_tensors_ = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

## Iterate

In [7]:
print("Elements of ds_tensors:")
for x in ds_tensors_:
    print(x)

print("\nElements in ds_file:")
for x in ds_file:
    print(x)

Elements of ds_tensors:
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 9 36], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3'], shape=(1,), dtype=string)
